### ISSUE TITLE
Support Doom3 demo maps

### ISSUE THREAD

**Issue by christhalinger** [blackbeard334/djoom3#19]
@blackbeard334 and I already talked about this but I would like to have a tracking bug here.  Here is the current output when running the demo on macOS:

```
DOOM 1.3.1.1 win-x86 Wed Sep 26 15:26:51 CEST 2018
0 MHz Intel CPU with MMX & SSE & SSE2 & SSE3 & HT
17179 MB System Memory
0 MB Video Memory
Winsock Initialized
Found interface: utun2 utun2 - 
Found interface: utun1 utun1 - 
Found interface: utun0 utun0 - 
Found interface: awdl0 awdl0 - 
Found interface: en0 en0 - 192.168.0.87/64
Found interface: lo0 lo0 - 127.0.0.1/64
------ Initializing File System ------
Loaded pk4 /Users/cthalinger/djoom3/base/demo00.pk4 with checksum 0xb7af8b02
Current search path:
/Users/cthalinger/djoom3/base
/Users/cthalinger/djoom3/base/demo00.pk4 (12234 files - 0xb7af8b02 not referenced)
game DLL: 0x0 in pak: 0x0
Addon pk4s:
file syastem initialized.
--------------------------------------
^3WARNING: ^1idFileSystemLocal::StartBackgroundDownloadThread: failed
----- Initializing Decls -----
^1...loading 'materials/aaduffytest.mtr'
^1...loading 'materials/alphalabs.mtr'
^1...loading 'materials/andy.mtr'
^1...loading 'materials/atest.mtr'
^1...loading 'materials/base_door.mtr'
^1...loading 'materials/base_floor.mtr'
^1...loading 'materials/base_light.mtr'
^1...loading 'materials/base_trim.mtr'
^1...loading 'materials/base_wall.mtr'
^1...loading 'materials/caves.mtr'
^1...loading 'materials/char_common.mtr'
^1...loading 'materials/characters.mtr'
^1...loading 'materials/d3xpchang.mtr'
^1...loading 'materials/decals.mtr'
^1...loading 'materials/door.mtr'
^1...loading 'materials/duffytest.mtr'
^1...loading 'materials/fogs.mtr'
^1...loading 'materials/gfx.mtr'
^1...loading 'materials/glass.mtr'
^1...loading 'materials/hell.mtr'
^1...loading 'materials/invisible.mtr'
^1...loading 'materials/jerry.mtr'
^1...loading 'materials/kentest.mtr'
^1...loading 'materials/ktest.mtr'
^1...loading 'materials/lab.mtr'
^1...loading 'materials/lab_floor.mtr'
^1...loading 'materials/lights.mtr'
^1...loading 'materials/mal.mtr'
^1...loading 'materials/mapobjects.mtr'
^1...loading 'materials/maxtextures.mtr'
^1...loading 'materials/monsters.mtr'
^1...loading 'materials/morgue.mtr'
^1...loading 'materials/mp_gui.mtr'
^1...loading 'materials/mp_lights.mtr'
^1...loading 'materials/mre.mtr'
^1...loading 'materials/object.mtr'
^1...loading 'materials/outside.mtr'
^1...loading 'materials/patd.mtr'
^1...loading 'materials/patrick_d3ex.mtr'
^1...loading 'materials/patricktest.mtr'
^1...loading 'materials/pdtest.mtr'
^1...loading 'materials/phook.mtr'
^1...loading 'materials/recyc_door.mtr'
^1...loading 'materials/recyc_floor.mtr'
^1...loading 'materials/recyc_light.mtr'
^1...loading 'materials/recyc_trim.mtr'
^1...loading 'materials/recyc_wall.mtr'
^1...loading 'materials/rock.mtr'
^1...loading 'materials/scabby.mtr'
^1...loading 'materials/senetemp.mtr'
^1...loading 'materials/sfx.mtr'
^1...loading 'materials/sfx_multiplayer.mtr'
^1...loading 'materials/shaderdemo.mtr'
^1...loading 'materials/skies.mtr'
^1...loading 'materials/sound.mtr'
^1...loading 'materials/specialcase.mtr'
^1...loading 'materials/stevetest.mtr'
^1...loading 'materials/stone.mtr'
^1...loading 'materials/testinteractions.mtr'
^1...loading 'materials/tim.mtr'
^1...loading 'materials/tools.mtr'
^1...loading 'materials/vehicles.mtr'
^1...loading 'materials/video.mtr'
^1...loading 'materials/vp_materials.mtr'
^1...loading 'materials/washroom.mtr'
^1...loading 'materials/weapons.mtr'
^1...loading 'materials/zgraeme.mtr'
^1...loading 'skins/skins.skin'
^1...loading 'skins/skins_characters_npcs.skin'
^1...loading 'skins/skins_characters_player.skin'
^1...loading 'skins/skins_characters_suit.skin'
^1...loading 'skins/skins_characters_suit_old.skin'
^1...loading 'skins/skins_models_chars_labcoat.skin'
^1...loading 'skins/skins_models_chars_maint.skin'
^1...loading 'skins/skins_models_chars_marine.skin'
^1...loading 'skins/skins_models_chars_sarge.skin'
^1...loading 'skins/skins_models_chars_security.skin'
^1...loading 'skins/skins_models_chars_suit.skin'
^1...loading 'skins/skins_models_mapobjects.skin'
^1...loading 'skins/skins_models_mapobjects_doors_hazdoor1.skin'
^1...loading 'skins/skins_models_monsters.skin'
^1...loading 'skins/skins_models_props.skin'
^1...loading 'skins/skins_models_weapons.skin'
^1...loading 'skins/skins_monsters_zombie_chaingun.skin'
^1...loading 'skins/skins_monsters_zombies.skin'
^1...loading 'skins/skins_npcs.skin'
^1...loading 'skins/skins_player.skin'
^1...loading 'skins/skins_poppy.skin'
^1...loading 'skins/skins_security.skin'
^1...loading 'skins/skins_teleporter.skin'
^1...loading 'skins/skins_uacmarine.skin'
^1...loading 'skins/skins_zcc.skin'
^1...loading 'skins/skins_zmaint.skin'
^1...loading 'skins/skins_zsec.skin'
^1...loading 'sound/actions.sndshd'
^1...loading 'sound/admin.sndshd'
^1...loading 'sound/alarms.sndshd'
^1...loading 'sound/alpha_labs21.sndshd'
^1...loading 'sound/alphalabs1.sndshd'
^1...loading 'sound/alphalabs3.sndshd'
^1...loading 'sound/audiologs.sndshd'
^1...loading 'sound/bloopers.sndshd'
^1...loading 'sound/boxsounds.sndshd'
^1...loading 'sound/bubbles.sndshd'
^1...loading 'sound/caverns2.sndshd'
^1...loading 'sound/chris.sndshd'
^1...loading 'sound/commoutside.sndshd'
^1...loading 'sound/computers.sndshd'
^1...loading 'sound/cpu.sndshd'
^1...loading 'sound/creepy_elements.sndshd'
^1...loading 'sound/default.sndshd'
^1...loading 'sound/delta1.sndshd'
^1...loading 'sound/delta2a.sndshd'
^1...loading 'sound/delta2b.sndshd'
^1...loading 'sound/delta3.sndshd'
^1...loading 'sound/delta4.sndshd'
^1...loading 'sound/delta5.sndshd'
^1...loading 'sound/doors.sndshd'
^1...loading 'sound/duffy.sndshd'
^1...loading 'sound/e3.sndshd'
^1...loading 'sound/e3_drones.sndshd'
^1...loading 'sound/e3_plain.sndshd'
^1...loading 'sound/electrical.sndshd'
^1...loading 'sound/enpro.sndshd'
^1...loading 'sound/fans.sndshd'
^1...loading 'sound/game.sndshd'
^1...loading 'sound/gui.sndshd'
^1...loading 'sound/guitest.sndshd'
^1...loading 'sound/headtest.sndshd'
^1...loading 'sound/hell.sndshd'
^1...loading 'sound/items.sndshd'
^1...loading 'sound/johnc.sndshd'
^1...loading 'sound/ken.sndshd'
^1...loading 'sound/lights.sndshd'
^1...loading 'sound/lightsout.sndshd'
^1...loading 'sound/machinery.sndshd'
^1...loading 'sound/map10.sndshd'
^1...loading 'sound/map_alphalabs4.sndshd'
^1...loading 'sound/map_comm1.sndshd'
^1...loading 'sound/map_cpu.sndshd'
^1...loading 'sound/map_cpuboss.sndshd'
^1...loading 'sound/map_ending.sndshd'
^1...loading 'sound/map_hellhole.sndshd'
^1...loading 'sound/map_marscity2.sndshd'
^1...loading 'sound/map_site3.sndshd'
^1...loading 'sound/marscity.sndshd'
^1...loading 'sound/mc_underground.sndshd'
^1...loading 'sound/mc_underground_chars.sndshd'
^1...loading 'sound/metals.sndshd'
^1...loading 'sound/monorail.sndshd'
^1...loading 'sound/monster_boss_sabaoth.sndshd'
^1...loading 'sound/monster_demon_archvile.sndshd'
^1...loading 'sound/monster_demon_bruiser.sndshd'
^1...loading 'sound/monster_demon_cacodemon.sndshd'
^1...loading 'sound/monster_demon_cherub.sndshd'
^1...loading 'sound/monster_demon_cyberdemon.sndshd'
^1...loading 'sound/monster_demon_guardian.sndshd'
^1...loading 'sound/monster_demon_hellknight.sndshd'
^1...loading 'sound/monster_demon_imp.sndshd'
^1...loading 'sound/monster_demon_lostsoul.sndshd'
^1...loading 'sound/monster_demon_maggot.sndshd'
^1...loading 'sound/monster_demon_mancubus.sndshd'
^1...loading 'sound/monster_demon_pinky.sndshd'
^1...loading 'sound/monster_demon_revenant.sndshd'
^1...loading 'sound/monster_demon_tick.sndshd'
^1...loading 'sound/monster_demon_trite.sndshd'
^1...loading 'sound/monster_demon_vagary.sndshd'
^1...loading 'sound/monster_demon_wraith.sndshd'
^1...loading 'sound/monster_zombie_bernie.sndshd'
^1...loading 'sound/monster_zombie_boney.sndshd'
^1...loading 'sound/monster_zombie_chainsaw.sndshd'
^1...loading 'sound/monster_zombie_civilian.sndshd'
^1...loading 'sound/monster_zombie_commando.sndshd'
^1...loading 'sound/monster_zombie_fat.sndshd'
^1...loading 'sound/monster_zombie_maint.sndshd'
^1...loading 'sound/monster_zombie_morgue.sndshd'
^1...loading 'sound/monster_zombie_scientist.sndshd'
^1...loading 'sound/monster_zombie_security.sndshd'
^1...loading 'sound/monsters.sndshd'
^1...loading 'sound/moveable.sndshd'
^1...loading 'sound/mpsounds.sndshd'
^1...loading 'sound/multiplayer.sndshd'
^1...loading 'sound/music.sndshd'
^1...loading 'sound/outdoor.sndshd'
^1...loading 'sound/player.sndshd'
^1...loading 'sound/radio.sndshd'
^1...loading 'sound/recycling.sndshd'
^1...loading 'sound/rooms.sndshd'
^1...loading 'sound/roq.sndshd'
^1...loading 'sound/soundscape.sndshd'
^1...loading 'sound/speaker_test.sndshd'
^1...loading 'sound/tele_in.sndshd'
^1...loading 'sound/tim_temp.sndshd'
^1...loading 'sound/video.sndshd'
^1...loading 'sound/vo.sndshd'
^1...loading 'sound/voc.sndshd'
^1...loading 'sound/weapons.sndshd'
^1...loading 'sound/whispers.sndshd'
^1...loading 'sound/world_ambience.sndshd'
^1...loading 'sound/xian.sndshd'
^1...loading 'sound/zombie_sight_hack.sndshd'
------------------------------
^1idFileSystem::OpenExplicitFileRead - reading from: /Users/cthalinger/djoom3/base/config.spec
^1writing to: /Users/cthalinger/djoom3/base/config.spec
Detected
 	4 x 0.00 GHz CPU
	17179 MB of System memory
	512 MB of Video memory on an optimal video architecture

This system qualifies for Low quality.
------- Initializing renderSystem --------
using ARB renderSystem
renderSystem initialized.
--------------------------------------
5151 strings read from strings/english.lang
Couldn't open journal files
couldn't exec editor.cfg
execing default.cfg
couldn't exec DoomConfig.cfg
couldn't exec autoexec.cfg
5151 strings read from strings/english.lang
----- Initializing Sound System ------
Setup OpenAL device and context... Done.
OpenAL: EAX 4.0 extension not found
OpenAL: found OpenAL Soft
OpenAL: found 256 hardware voices
sound system initialized.
--------------------------------------
----- R_InitOpenGL -----
Initializing OpenGL subsystem
...calling CDS: ok

------- Input Initialization -------
mouse: DirectInput initialized.
keyboard: DirectInput initialized.
------------------------------------
...using GL_ARB_multitexture
...using GL_ARB_texture_env_combine
...using GL_ARB_texture_cube_map
...using GL_ARB_texture_env_dot3
...using GL_ARB_texture_env_add
...using GL_ARB_texture_non_power_of_two
...using GL_ARB_texture_compression
...using GL_EXT_texture_compression_s3tc
...using GL_EXT_texture_filter_anisotropic
   maxTextureAnisotropy: 16.000000
...using GL_EXT_texture_lod
...using GL_1.4_texture_lod_bias
X..GL_EXT_shared_texture_palette not found
X..GL_EXT_texture3D not found
...using GL_EXT_stencil_wrap
X..GL_NV_register_combiners not found
...using GL_EXT_stencil_two_side
X..GL_ATI_fragment_shader not found
X..GL_ATI_text_fragment_shader not found
...using GL_ARB_vertex_buffer_object
...using GL_ARB_vertex_program
...using GL_ARB_fragment_program
X..EXT_depth_bounds_test not found
---------- R_NV20_Init ----------
Not available.
----------- R200_Init -----------
Not available.
---------- R_ARB2_Init ----------
Available.
---------------------------------
----- R_ReloadARBPrograms -----
glprogs/test.vfpException in thread "main" java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL43.glGetDebugMessageLog(GL43.java:576)
	at neo.Renderer.qgl.checkGLError(qgl.java:1821)
	at neo.Renderer.qgl.qglGetError(qgl.java:803)
	at neo.Renderer.draw_arb2.R_LoadARBProgram(draw_arb2.java:531)
	at neo.Renderer.draw_arb2$R_ReloadARBPrograms_f.run(draw_arb2.java:619)
	at neo.Renderer.RenderSystem_init.R_InitOpenGL(RenderSystem_init.java:2080)
	at neo.Renderer.tr_local$idRenderSystemLocal.InitOpenGL(tr_local.java:1455)
	at neo.framework.Common$idCommonLocal.InitRenderSystem(Common.java:1852)
	at neo.framework.Common$idCommonLocal.InitGame(Common.java:1478)
	at neo.framework.Common$idCommonLocal.Init(Common.java:543)
	at neo.sys.win_main.main(win_main.java:1686)
^CAL lib: (EE) alc_cleanup: 2 devices not closed
```

**Comment by blackbeard334** [comment]
Fixed in #21
